import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import Footer from '@/components/Footer';
import Header from '@/components/Header';

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
});
export const metadata: Metadata = {
  title: 'Movies Recommendation',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <Header />
        <main className='bg-[#04152d] py-20'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
