import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import { TmdbContextProvider } from '@/context/tmdb-context';

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
});
export const metadata: Metadata = {
  title: 'Movies Recommendation',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <TmdbContextProvider>
        <body className={roboto.className}>
          <Header />
          {children}
          <Footer />
        </body>
      </TmdbContextProvider>
    </html>
  );
}
